version: "3"
services:
  mc_boilerplate:
    build: .
    environment:
      - WORKFLOW_USER_API_KEY
      - WORKFLOW_USER_API_SECRET
      - LEGACY_USER_API_KEY
      - LEGACY_USER_API_SECRET
    volumes:
      - ./logs:/usr/src/app/logs

networks:
  default:
    external:
      name: managed-connector
